server:
  port: 9100
eureka:
  instance:
    hostname: eureka9100
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://eureka9200:9200/eureka
spring:
  application:
    name: eureka9100